"""Write the shared site assets for the enabled components (review D5, D10).

    python -m biblecore assets

  css/core.css             shared structure, from biblecore/web/core.css
  css/components.css       each enabled component's style.css
  data/components.json     [{name, role, selector}] for app/main.js + spotlight.js
  components-reference.md  each enabled component's snippet (synced)
  css/division.css         the book's division theme: tokens, dark mode,
                           banner masthead + emblem, ornament (theme.py)
  index.html, app/*.js     the app shell, from biblecore/web/ (0.11.0;
                           structural audit F1): the book name filled in,
                           every same-origin link and import stamped
                           `?v=<content hash>` (F2)

All generated, so don't edit them. The book's own look is css/theme.css. Runs
first in the build, since validate's whitelist reads every css/*.css.

Cache-busting: a module's hash covers its text after its own imports are
stamped, so a change in threads.js changes search.js's and main.js's URLs
too, and index.html's hashes cover each stylesheet as the build left it
(theme.css included). The same inputs give the same bytes, so a rebuild
changes nothing.

A book whose `paths.css` points at a single stylesheet (Joshua's old layout,
in the tests) keeps it: nothing is written into css/ then, no shell either,
only the data file and the reference.
"""
import hashlib
import json
import os
import re

from biblecore import components
from biblecore.book import book

HERE = os.path.dirname(os.path.abspath(__file__))
WEB = os.path.join(HERE, "web")

# `from "./x.js"`, `import "./x.js"`, `import("./x.js")`: same-origin modules
IMPORT_RE = re.compile(r"""(\bfrom\s*|\bimport\s*\(?\s*)(["'])\./([\w.-]+\.js)\2""")
# index.html's stylesheet and script links
LINK_RE = re.compile(r'\b((?:href|src)=")((css|app)/([\w.-]+\.(?:css|js)))"')
JS_MARK = ("// Generated by `python -m biblecore assets` from bible-core's "
           "biblecore/web/app/{name}.\n// Don't edit it here: the next build "
           "overwrites it. Change it in bible-core.\n")
HTML_MARK = ("<!-- Generated by `python -m biblecore assets` from bible-core's "
             "biblecore/web/index.html.\n     Don't edit it here: the next build "
             "overwrites it. Change it in bible-core. -->\n")


def _write(path, text):
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != text:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        return True
    return False


def _hash(text):
    # LF, so a Windows and a Linux build stamp the same bytes (what Pages serves)
    return hashlib.sha256(text.replace("\r\n", "\n").encode("utf-8")).hexdigest()[:10]


def _read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def shell(b, css=None):
    """{relative path: text} of the app shell for book `b`, hashed. A
    stylesheet's hash is taken from `css` ({file name: text}, the ones this
    build writes) or else read from the book's css folder (theme.css); a
    missing one is linked without a `?v`."""
    css = css or {}
    css_dir = b.path("css")
    app = os.path.join(WEB, "app")
    src = {f: _read(os.path.join(app, f)) for f in sorted(os.listdir(app)) if f.endswith(".js")}
    out, hashes = {}, {}

    def render(name, stack):
        if name in hashes:
            return
        if name in stack:
            raise ValueError(f"app shell: import cycle {' -> '.join(stack + (name,))}; "
                             f"content hashes need an acyclic import graph")
        text = src[name]
        for m in IMPORT_RE.finditer(text):
            if m[3] not in src:
                raise ValueError(f"app shell: {name} imports ./{m[3]}, not in biblecore/web/app/")
            render(m[3], stack + (name,))
        text = IMPORT_RE.sub(lambda m: f"{m[1]}{m[2]}./{m[3]}?v={hashes[m[3]]}{m[2]}", text)
        text = JS_MARK.format(name=name) + text
        out[f"app/{name}"] = text
        hashes[name] = _hash(text)

    for name in src:
        render(name, ())

    def stamp(m):
        folder, file = m[3], m[4]
        if folder == "app":
            if file not in hashes:
                raise ValueError(f"app shell: index.html links app/{file}, not in biblecore/web/app/")
            v = hashes[file]
        else:
            path = os.path.join(css_dir, file)
            if file in css:
                v = _hash(css[file])
            elif os.path.exists(path):
                v = _hash(_read(path))
            else:
                return m[0]
        return f'{m[1]}{m[2]}?v={v}"'

    html = _read(os.path.join(WEB, "index.html")).replace("{{BOOK}}", b.name)
    html = LINK_RE.sub(stamp, html)
    head, sep, rest = html.partition("\n")
    out["index.html"] = (head + sep + HTML_MARK + rest if head.lower().startswith("<!doctype")
                         else HTML_MARK + html)
    return out


def generated(b, comps=None):
    """{path relative to the book root: text} for the stylesheets and the
    app shell this book gets, in write order; {} for a book whose css is a
    single file."""
    css = b.path("css")
    if not os.path.isdir(css):
        return {}
    from biblecore import theme
    comps = components.enabled(b) if comps is None else comps
    sheets = {"core.css": _read(os.path.join(WEB, "core.css")),
              "components.css": components.css_bundle(comps)}
    division = theme.build_css(b)
    if division:
        sheets["division.css"] = division
    rel = os.path.relpath(css, b.root).replace(os.sep, "/")
    out = {f"{rel}/{name}": text for name, text in sheets.items()}
    # after the stylesheets, since index.html carries their hashes
    out.update(shell(b, sheets))
    return out


def main(argv=None):
    b = book()
    comps = components.enabled(b)
    wrote = []
    for rel, text in generated(b, comps).items():
        if _write(os.path.join(b.root, rel), text):
            wrote.append(rel)
    data = json.dumps(components.app_manifest(comps), indent=2, ensure_ascii=False) + "\n"
    if _write(b.data("components.json"), data):
        wrote.append("data/components.json")
    if _write(b.path("components_ref"), components.reference(comps, b.name)):
        wrote.append(os.path.basename(b.path("components_ref")))
    print(f"assets: components {[c.name for c in comps]}"
          + (f"; wrote {', '.join(wrote)}" if wrote else "; up to date"))
    return 0
