"""data/manifest.json: the index to a book's published data (review F17).

    python -m biblecore manifest

The site's data/*.json files are a public, static API: the hub and any
other tool read them. The manifest says which book this is, which core
built it, how far along it is, and which schema version each file follows.
Shapes are documented in bible-core's docs/data-shapes.md. When a shape
changes incompatibly, bump its number in SCHEMAS so readers can tell.

Deterministic (no timestamps), so re-running the build changes nothing.
"""
import json
import os

from biblecore import __version__
from biblecore.book import book

# file -> schema version (docs/data-shapes.md)
SCHEMAS = {
    "units.json": 1,
    "threads.json": 1,
    "roots.json": 1,
    "occurrences.json": 1,
    "canon.json": 1,
    "palette.json": 1,
    "components.json": 1,
    "lemmas.json": 1,
    "text.json": 1,
    "words/": 1,
}


def build():
    b = book()
    units = json.load(open(b.data("units.json"), encoding="utf-8"))
    rows = units.get("units", [])
    files = {name: {"schema": v} for name, v in SCHEMAS.items()
             if os.path.exists(b.data(name.rstrip("/")))}
    # data files written by later steps (text/, words/, lemmas.json) add
    # themselves here as they arrive
    return {
        "_note": "Index to this book's data/*.json. Shapes: bible-core "
                 "docs/data-shapes.md. Generated by the build; don't hand-edit.",
        "book": b.name,
        "slug": b.slug,
        "osis": b.osis,
        "abbrev": b.abbrev,
        "language": b.cfg.get("language"),
        "versification": b.cfg.get("versification", "kjv"),
        "core": __version__,
        "hub": b.cfg.get("hub"),
        "unit_count": units.get("unit_count", len(rows)),
        "units_built": sum(1 for u in rows if u.get("built")),
        "files": files,
    }


def main(argv=None):
    m = build()
    path = book().data("manifest.json")
    new = json.dumps(m, indent=2, ensure_ascii=False) + "\n"
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if new != old:
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(new)
    print(f"manifest: {m['units_built']}/{m['unit_count']} units built, "
          f"{len(m['files'])} data files")
    return 0
