"""Apply the book's retrofit-tags.json (hand-authored) and retro-tags.json
(generated by the porter from later units' threads.retro) to units/*.html.

    python -m biblecore retrofit

Pure HTML-text edits, language-neutral. `add`/`retag` take an optional `w`
(inject/update data-w); `retag_word` deliberately doesn't (a bulk
reclassification changes the root, not the word). Idempotent -- every op
no-ops once applied, so the build re-runs it every time.

  strip_span   whole unit: unwrap every <span class="CLS">…</span>, keeping the
               inner text
  add          wrap the first untagged occurrence of `text` in verse `verse`
               (optional "cls": "rl" for a root-linked, uncounted span, default
                "r"; optional "nth": 2 to pick the 2nd .v block with that number
                in a cross-chapter unit; optional "w": OSHB word id, required
                by unit_meta.validate() when `root` is a tracked thread)
  retag        change data-root on the span wrapping `text` in `verse`
               (optional "w": inject/update data-w on the retagged span --
               needed when retagging a previously-local span onto a tracked
               thread, which had no data-w before; optional "occ": 1-based
               index picking the Nth span with this root+text in the verse,
               when the same root renders the same English text more than
               once in one verse and a bare search can't tell them apart)
  unwrap       strip the data-root span around every `text` (whole unit)
  retag_word   whole unit: any `<span … data-root="from" …>TEXT</span> whose
               TEXT matches the `match` regex -> data-root="to" (no `w` --
               see module docstring)
  untag_word   whole unit: unwrap data-root="root" spans whose TEXT matches
               `match` (or, with `nomatch`, whose TEXT does NOT match)
  text         plain find/replace in the unit's visible text (wording fixes)
"""

import json
import os
import re
import sys

from biblecore.book import book

SPAN = r'<span class="r[l]?"[^>]*\bdata-root="%s"[^>]*>([^<]*)</span>'


def vblock(html, verse, nth=1):
    """(start, end) of the nth .v block whose number is `verse`. `nth` (default
    1) disambiguates cross-chapter units where a bare verse number repeats."""
    pat = re.compile(r'<(?:div|p) class="v">(?:(?!</(?:div|p)>).)*?<span class="n">'
                     + re.escape(str(verse)) + r'</span>.*?</(?:div|p)>', re.S)
    hits = list(pat.finditer(html))
    if len(hits) < nth:
        return None
    m = hits[nth - 1]
    return (m.start(), m.end())


def apply_add(html, it):
    nth = it.get("nth", 1)
    span = vblock(html, it["verse"], nth)
    if not span:
        return html, f"SKIP {it['unit']} v{it['verse']}: no .v block"
    a, b = span
    seg = html[a:b]
    cls = it.get("cls", "r")
    w_attr = f' data-w="{it["w"]}"' if it.get("w") else ""
    tag = f'<span class="{cls}" data-root="{it["root"]}"{w_attr}>{it["text"]}</span>'
    already = re.search(r'<span class="r[l]?" data-root="%s"[^>]*>%s</span>'
                        % (re.escape(it["root"]), re.escape(it["text"])), seg)
    if already:
        return html, f"ok   {it['unit']} v{it['verse']} {it['root']}: already tagged"
    pat = re.compile(r'(?<![\w-])' + re.escape(it["text"]) + r'(?![\w-])')
    hit = _first_outside_tags(seg, pat)
    if hit is None:
        return html, f"MISS {it['unit']} v{it['verse']}: '{it['text']}' not free in verse"
    i, j = hit
    seg = seg[:i] + tag + seg[j:]
    return html[:a] + seg + html[b:], f"ADD  {it['unit']} v{it['verse']} {it['root']}: '{it['text']}'"


def apply_retag(html, it):
    """`occ` (default 1) picks the Nth from-match in the verse, left to
    right -- needed when the same root produces the same English text twice
    in one verse (e.g. two untagged-w "possess" spans from one Hebrew word
    each), which a bare .search() can't tell apart. Idempotency for occ>1
    is checked by data-w already matching at that same position, since
    already_pat (used for the occ=1/from!=to case) can't distinguish which
    of several same-text spans a replay is asking about."""
    span = vblock(html, it["verse"], it.get("nth", 1))
    if not span:
        return html, f"SKIP {it['unit']} v{it['verse']}: no .v block"
    a, b = span
    seg = html[a:b]
    w = it.get("w")
    occ = it.get("occ", 1)

    # Match the whole opening <span ...> for this data-root/text so
    # data-root and (optionally) data-w can be rewritten together.
    open_pat = re.compile(
        r'<span class="(r[l]?)"([^>]*)\bdata-root="' + re.escape(it["from"])
        + r'"([^>]*)>' + re.escape(it["text"]) + r'</span>')
    matches = list(open_pat.finditer(seg))

    already_pat = re.compile(
        r'<span class="r[l]?"[^>]*\bdata-root="' + re.escape(it["to"])
        + r'"[^>]*>' + re.escape(it["text"]) + r'</span>')
    if len(matches) < occ:
        if already_pat.search(seg):
            return html, f"ok   {it['unit']} v{it['verse']}: already retagged"
        return html, (f"MISS {it['unit']} v{it['verse']}: data-root=\"{it['from']}\">"
                       f"{it['text']} not present (occ {occ})")

    m = matches[occ - 1]
    if w and it["from"] == it["to"] and f'data-w="{w}"' in m.group(0):
        return html, f"ok   {it['unit']} v{it['verse']}: occurrence {occ} already data-w={w}"

    cls, before, after = m.group(1), m.group(2), m.group(3)
    attrs = (before + " " + after).strip()
    if w:
        if "data-w=" in attrs:
            attrs = re.sub(r'data-w="[^"]*"', f'data-w="{w}"', attrs)
        else:
            attrs = (attrs + f' data-w="{w}"').strip()
    attrs_str = f" {attrs}" if attrs else ""
    new_open = f'<span class="{cls}" data-root="{it["to"]}"{attrs_str}>{it["text"]}</span>'
    seg = seg[:m.start()] + new_open + seg[m.end():]
    return html[:a] + seg + html[b:], \
        f"RTAG {it['unit']} v{it['verse']}: {it['from']}->{it['to']} '{it['text']}'"


def apply_unwrap(html, it):
    pat = re.compile(
        r'<span class="r[l]?"[^>]*\bdata-root="' + re.escape(it["root"]) + r'"[^>]*>'
        + re.escape(it["text"]) + r'</span>')
    new, n = pat.subn(it["text"], html)
    return new, (f"UNWR {it['unit']}: {n}x '{it['text']}' (was {it['root']})"
                 if n else f"ok   {it['unit']} unwrap '{it['text']}': nothing")


def apply_retag_word(html, it):
    m_re = re.compile(it["match"], re.I)
    n = [0]

    def repl(mm):
        if m_re.search(mm.group(1)):
            n[0] += 1
            return mm.group(0).replace(f'data-root="{it["from"]}"',
                                       f'data-root="{it["to"]}"', 1)
        return mm.group(0)

    new = re.sub(SPAN % re.escape(it["from"]), repl, html)
    return new, (f"RTAGW {it['unit']}: {n[0]}x {it['from']}->{it['to']} /{it['match']}/"
                 if n[0] else f"ok    {it['unit']} retag_word {it['from']}: no hit")


def apply_untag_word(html, it):
    pos = it.get("match")
    neg = it.get("nomatch")
    pr = re.compile(pos, re.I) if pos else None
    nr = re.compile(neg, re.I) if neg else None
    n = [0]

    def repl(mm):
        txt = mm.group(1)
        drop = (pr and pr.search(txt)) or (nr and not nr.search(txt))
        if drop:
            n[0] += 1
            return txt
        return mm.group(0)

    new = re.sub(SPAN % re.escape(it["root"]), repl, html)
    return new, (f"UNTGW {it['unit']}: {n[0]}x untag {it['root']}"
                 if n[0] else f"ok    {it['unit']} untag_word {it['root']}: no hit")


def apply_text(html, it):
    if it["to"] in html and it["from"] not in html:
        return html, f"ok   {it['unit']} text '{it['from']}': already applied"
    new, n = re.subn(re.escape(it["from"]), it["to"].replace("\\", "\\\\"), html)
    return new, (f"TEXT {it['unit']}: {n}x '{it['from']}' -> '{it['to']}'"
                 if n else f"MISS {it['unit']} text: '{it['from']}' not found")


def apply_strip_span(html, it):
    """Unwrap every <span class="CLS">…</span> in the unit, keeping inner text."""
    cls = re.escape(it["class"])
    pat = re.compile(r'<span class="' + cls + r'">(.*?)</span>', re.S)
    new, n = pat.subn(r"\1", html)
    return new, (f"STRIP {it['unit']}: {n}x span.{it['class']}"
                 if n else f"ok   {it['unit']} strip span.{it['class']}: none")


def _first_outside_tags(seg, pat):
    depth = 0
    for k, ch in enumerate(seg):
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth = max(0, depth - 1)
        elif depth == 0 and pat.match(seg, k):
            m = pat.match(seg, k)
            return m.start(), m.end()
    return None


FNS = {"add": apply_add, "retag": apply_retag, "unwrap": apply_unwrap,
       "retag_word": apply_retag_word, "untag_word": apply_untag_word,
       "text": apply_text, "strip_span": apply_strip_span}
ORDER = ["strip_span", "text", "untag_word", "retag_word", "unwrap", "retag", "add"]


def load_specs(spec_path=None, retro_path=None):
    spec_path = spec_path or book().path("retrofit")
    retro_path = retro_path or book().path("retro")
    spec = {}
    if os.path.exists(spec_path):
        with open(spec_path, encoding="utf-8") as fh:
            spec = json.load(fh)
    if os.path.exists(retro_path):
        with open(retro_path, encoding="utf-8") as fh:
            retro = json.load(fh)
        for op, items in retro.items():
            if isinstance(items, list):
                spec.setdefault(op, []).extend(items)
    return spec


def main(argv=None):
    spec = load_specs()
    by_unit = {}
    for op in ORDER:
        for it in spec.get(op, []):
            if "unit" not in it:  # skip inline "_c" comment entries
                continue
            by_unit.setdefault(it["unit"], []).append((op, it))

    logs = []
    for unit, items in sorted(by_unit.items()):
        path = os.path.join(book().path("units"), unit + ".html")
        if not os.path.exists(path):
            logs.append(f"SKIP {unit}: no such fragment")
            continue
        with open(path, encoding="utf-8") as fh:
            before = fh.read()
        html = before
        for op, it in items:
            html, msg = FNS[op](html, it)
            logs.append(msg)
        if html != before:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(html)

    for m in logs:
        print(m)
    if any(m.startswith(("MISS", "SKIP")) for m in logs):
        return 1
    return 0
