"""The component registry (review D5, D10, E13).

Each optional component is one folder here. Its pieces ship together:

    <name>/component.json   {name, summary, classes, role, selector, since}
    <name>/style.css        its CSS (uses theme.css tokens only)
    <name>/__init__.py      check(html, meta) -> [problems]
    <name>/snippet.md       its style-reference text (markup, rules, why)

A book enables components in book.json "components". Any unit may use any
enabled one, since the porter needs no per-unit genre (E13). The build (`assets`
step) then writes:

    css/core.css            the shared structure (biblecore/web/core.css)
    css/components.css      style.css of each enabled component
    data/components.json    [{name, role, selector}] for the app shell
    components-reference.md the snippets, synced to the project side

The whitelist check reads every css/*.css, so a class from a component the
book hasn't enabled fails validation by name. Each check runs only on units
whose contract is at or past the component's `since` (contract.py).

`role` tells the app shell what to do with the component:
  verse-aside   a following sibling of a verse, collapsed into the verse note
                with the glosses (spotlight.js)
  inline-block  a section.block that stays where the text puts it instead of
                being hoisted with the structure blocks (main.js)
  verse         markup inside or around verse blocks; nothing to do
"""
import importlib
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROLES = ("verse-aside", "inline-block", "verse")
_KEYS = {"name", "summary", "classes", "role", "selector", "since"}


class Component:
    def __init__(self, folder):
        self.folder = folder
        with open(os.path.join(folder, "component.json"), encoding="utf-8") as fh:
            self.spec = json.load(fh)
        bad = set(self.spec) - _KEYS
        if bad or self.spec.get("role") not in ROLES:
            raise ValueError(f"{folder}/component.json: unknown keys {sorted(bad)} "
                             f"or role not in {ROLES}")
        self.name = self.spec["name"]

    def read(self, fname):
        p = os.path.join(self.folder, fname)
        return open(p, encoding="utf-8").read() if os.path.exists(p) else ""

    def check(self, html, meta):
        mod = importlib.import_module(f"biblecore.components.{self.name}")
        return mod.check(html, meta)


_registry = None


def registry():
    """name -> Component, for every folder with a component.json."""
    global _registry
    if _registry is None:
        _registry = {}
        for d in sorted(os.listdir(HERE)):
            if os.path.exists(os.path.join(HERE, d, "component.json")):
                c = Component(os.path.join(HERE, d))
                _registry[c.name] = c
    return _registry


def enabled(b=None):
    """The book's enabled components, in book.json order."""
    if b is None:
        from biblecore.book import book
        b = book()
    reg = registry()
    unknown = [n for n in b.components if n not in reg]
    if unknown:
        raise ValueError(f"book.json components {unknown} aren't in the registry "
                         f"(known: {sorted(reg)})")
    return [reg[n] for n in b.components]


def check(html, meta, unit_contract):
    """Every enabled component's check, gated by its `since`."""
    from biblecore import contract
    errs = []
    for c in enabled():
        if contract.at_least(unit_contract, c.spec["since"]):
            errs += c.check(html, meta)
    return errs


def css_bundle(comps):
    from biblecore import __version__
    parts = [f"/* components.css -- GENERATED by `python -m biblecore build` from "
             f"bible-core {__version__}\n   for this book's enabled components "
             f"({', '.join(c.name for c in comps) or 'none'}). Don't edit; "
             f"override in theme.css. */\n"]
    for c in comps:
        parts.append(f"\n/* ---- {c.name} ---- */\n" + c.read("style.css").rstrip("\n") + "\n")
    return "".join(parts)


def app_manifest(comps):
    return {"_note": "Enabled components for the app shell (biblecore/components). "
                     "Generated; don't edit.",
            "components": [{"name": c.name, "role": c.spec["role"],
                            "selector": c.spec["selector"]} for c in comps]}


def reference(comps, book_name):
    out = [f"# {book_name} — component reference\n",
           "Generated by `python -m biblecore build` from the components this "
           "book enables in `book.json`. Don't edit. The style reference's "
           "section 4 lists the base components and any book-specific notes. "
           "Any unit may use any component listed here.\n"]
    for c in comps:
        out.append(f"\n## {c.name} — {c.spec['summary']}\n\n" + c.read("snippet.md").strip() + "\n")
    return "\n".join(out)
